# Generated by Django 5.2.3 on 2025-07-17 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('couleur', models.CharField(help_text='Code couleur hexadécimal (ex: #FF5733)', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('drh', 'Directrice RH'), ('dp', 'Directeur Pays'), ('superieur', 'Supérieur hiérarchique'), ('collaborateur', 'Collaborateur')], max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('superieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nombre_jours', models.PositiveIntegerField(help_text="Nombre total de jours d'absence demandés")),
                ('raison', models.TextField(blank=True, null=True)),
                ('approuve_par_superieur', models.BooleanField(default=False)),
                ('date_approbation_superieur', models.DateField(blank=True, null=True)),
                ('verifie_par_drh', models.BooleanField(default=False)),
                ('date_verification_drh', models.DateField(blank=True, null=True)),
                ('valide_par_dp', models.BooleanField(default=False)),
                ('date_validation_dp', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve_superieur', 'Approuvé par supérieur'), ('verifie_drh', 'Vérifié par DRH'), ('valide_dp', 'Validé par DP'), ('rejete', 'Rejeté')], default='en_attente', max_length=30)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.typeabsence')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='absences.absence')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('jours_disponibles', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to=settings.AUTH_USER_MODEL)),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absences.typeabsence')),
            ],
            options={
                'unique_together': {('user', 'type_absence', 'annee')},
            },
        ),
    ]
