# Generated by Django 5.2.3 on 2025-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0002_profile_doit_changer_mdp_profile_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='nombre_jours',
            field=models.PositiveIntegerField(help_text='Nombre total de jours ouvrés demandés'),
        ),
    ]
